// Generated by Melange

import * as Caml_array from "melange.js/caml_array.js";
import * as Caml_int32 from "melange.js/caml_int32.js";
import * as Caml_js_exceptions from "melange.js/caml_js_exceptions.js";
import * as Caml_obj from "melange.js/caml_obj.js";
import * as Coco_lib__Lexer from "./lexer.js";
import * as Coco_lib__Token from "./token.js";
import * as Curry from "melange.js/curry.js";
import * as Stdlib from "melange/stdlib.js";
import * as Stdlib__Array from "melange/array.js";
import * as Stdlib__Buffer from "melange/buffer.js";
import * as Stdlib__List from "melange/list.js";
import * as Stdlib__Printexc from "melange/printexc.js";
import * as Stdlib__Printf from "melange/printf.js";

function parse(tokens) {
  const arr = Stdlib__Array.of_list(tokens);
  const i = {
    contents: 0
  };
  const adv = function (param) {
    const t = Caml_array.get(arr, i.contents);
    i.contents = i.contents + 1 | 0;
    return t;
  };
  const expect = function (tok) {
    if (Caml_obj.caml_equal(Caml_array.get(arr, i.contents), tok)) {
      adv();
      return;
    } else {
      return Stdlib.failwith(Curry._2(Stdlib__Printf.sprintf({
        TAG: /* Format */ 0,
        _0: {
          TAG: /* String_literal */ 11,
          _0: "expected ",
          _1: {
            TAG: /* String */ 2,
            _0: /* No_padding */ 0,
            _1: {
              TAG: /* String_literal */ 11,
              _0: ", got ",
              _1: {
                TAG: /* String */ 2,
                _0: /* No_padding */ 0,
                _1: /* End_of_format */ 0
              }
            }
          }
        },
        _1: "expected %s, got %s"
      }), Coco_lib__Token.to_string(tok), Coco_lib__Token.to_string(Caml_array.get(arr, i.contents))));
    }
  };
  const accept = function (tok) {
    if (Caml_obj.caml_equal(Caml_array.get(arr, i.contents), tok)) {
      adv();
      return true;
    } else {
      return false;
    }
  };
  const is_id = function (param) {
    const match = Caml_array.get(arr, i.contents);
    if (/* tag */ typeof match === "number" || typeof match === "string" || match.TAG !== /* Id */ 2) {
      return false;
    } else {
      return true;
    }
  };
  const is_type = function (param) {
    const match = Caml_array.get(arr, i.contents);
    if (!/* tag */ (typeof match === "number" || typeof match === "string")) {
      return false;
    }
    switch (match) {
      case /* Void */ 24 :
      case /* Bool */ 25 :
      case /* Int */ 26 :
      case /* Float */ 27 :
        return true;
      default:
        return false;
    }
  };
  const rel_expr = function (param) {
    const e = add_expr();
    const match = Caml_array.get(arr, i.contents);
    if (!/* tag */ (typeof match === "number" || typeof match === "string")) {
      return e;
    }
    switch (match) {
      case /* Eq */ 9 :
      case /* Neq */ 10 :
      case /* Lt */ 11 :
      case /* Le */ 12 :
      case /* Gt */ 13 :
      case /* Ge */ 14 :
        break;
      default:
        return e;
    }
    const op = adv();
    return {
      TAG: /* EBin */ 3,
      _0: e,
      _1: op,
      _2: add_expr()
    };
  };
  const add_expr = function (param) {
    let _e = mult_expr();
    while (true) {
      const e = _e;
      const match = Caml_array.get(arr, i.contents);
      if (!/* tag */ (typeof match === "number" || typeof match === "string")) {
        return e;
      }
      switch (match) {
        case /* Or */ 1 :
        case /* Add */ 7 :
        case /* Sub */ 8 :
          break;
        default:
          return e;
      }
      const op = adv();
      _e = {
        TAG: /* EBin */ 3,
        _0: e,
        _1: op,
        _2: mult_expr()
      };
      continue;
    };
  };
  const mult_expr = function (param) {
    let _e = pow_expr();
    while (true) {
      const e = _e;
      const match = Caml_array.get(arr, i.contents);
      if (!/* tag */ (typeof match === "number" || typeof match === "string")) {
        return e;
      }
      switch (match) {
        case /* And */ 0 :
        case /* Mul */ 4 :
        case /* Div */ 5 :
        case /* Mod */ 6 :
          break;
        default:
          return e;
      }
      const op = adv();
      _e = {
        TAG: /* EBin */ 3,
        _0: e,
        _1: op,
        _2: pow_expr()
      };
      continue;
    };
  };
  const pow_expr = function (param) {
    const e = unary();
    if (Caml_obj.caml_equal(Caml_array.get(arr, i.contents), /* Pow */ 3)) {
      adv();
      return {
        TAG: /* EBin */ 3,
        _0: e,
        _1: /* Pow */ 3,
        _2: pow_expr()
      };
    } else {
      return e;
    }
  };
  const unary = function (param) {
    const match = Caml_array.get(arr, i.contents);
    if (!/* tag */ (typeof match === "number" || typeof match === "string")) {
      return primary();
    }
    switch (match) {
      case /* Not */ 2 :
        adv();
        return {
          TAG: /* ENot */ 2,
          _0: unary()
        };
      case /* Sub */ 8 :
        adv();
        const n = Caml_array.get(arr, i.contents);
        if (/* tag */ typeof n === "number" || typeof n === "string") {
          return {
            TAG: /* EBin */ 3,
            _0: {
              TAG: /* ELit */ 0,
              _0: {
                TAG: /* VInt */ 0,
                _0: 0
              }
            },
            _1: /* Sub */ 8,
            _2: unary()
          };
        }
        switch (n.TAG) {
          case /* IntVal */ 0 :
            adv();
            return {
              TAG: /* ELit */ 0,
              _0: {
                TAG: /* VInt */ 0,
                _0: -n._0 | 0
              }
            };
          case /* FloatVal */ 1 :
            adv();
            return {
              TAG: /* ELit */ 0,
              _0: {
                TAG: /* VFloat */ 1,
                _0: - n._0
              }
            };
          default:
            return {
              TAG: /* EBin */ 3,
              _0: {
                TAG: /* ELit */ 0,
                _0: {
                  TAG: /* VInt */ 0,
                  _0: 0
                }
              },
              _1: /* Sub */ 8,
              _2: unary()
            };
        }
      default:
        return primary();
    }
  };
  const primary = function (param) {
    const n = Caml_array.get(arr, i.contents);
    if (/* tag */ typeof n === "number" || typeof n === "string") {
      switch (n) {
        case /* True */ 28 :
          adv();
          return {
            TAG: /* ELit */ 0,
            _0: {
              TAG: /* VBool */ 2,
              _0: true
            }
          };
        case /* False */ 29 :
          adv();
          return {
            TAG: /* ELit */ 0,
            _0: {
              TAG: /* VBool */ 2,
              _0: false
            }
          };
        case /* Lparen */ 30 :
          adv();
          const e = rel_expr();
          expect(/* Rparen */ 31);
          return e;
        case /* Call */ 49 :
          adv();
          const s = Caml_array.get(arr, i.contents);
          let name;
          if (/* tag */ typeof s === "number" || typeof s === "string" || s.TAG !== /* Id */ 2) {
            name = Stdlib.failwith("expected id");
          } else {
            adv();
            name = s._0;
          }
          expect(/* Lparen */ 30);
          let args;
          if (accept(/* Rparen */ 31)) {
            args = /* [] */ 0;
          } else {
            const a = rel_expr();
            const loop = function (_acc) {
              while (true) {
                const acc = _acc;
                if (!accept(/* Comma */ 36)) {
                  return Stdlib__List.rev({
                    hd: a,
                    tl: acc
                  });
                }
                _acc = {
                  hd: rel_expr(),
                  tl: acc
                };
                continue;
              };
            };
            const args$1 = loop(/* [] */ 0);
            expect(/* Rparen */ 31);
            args = args$1;
          }
          return {
            TAG: /* ECall */ 4,
            _0: name,
            _1: args
          };
        default:
          return Stdlib.failwith("expected expression");
      }
    } else {
      switch (n.TAG) {
        case /* IntVal */ 0 :
          adv();
          return {
            TAG: /* ELit */ 0,
            _0: {
              TAG: /* VInt */ 0,
              _0: n._0
            }
          };
        case /* FloatVal */ 1 :
          adv();
          return {
            TAG: /* ELit */ 0,
            _0: {
              TAG: /* VFloat */ 1,
              _0: n._0
            }
          };
        case /* Id */ 2 :
          adv();
          if (accept(/* Lbrack */ 34)) {
            rel_expr();
            expect(/* Rbrack */ 35);
          }
          return {
            TAG: /* EVar */ 1,
            _0: n._0
          };
      }
    }
  };
  const statement = function (param) {
    const name = Caml_array.get(arr, i.contents);
    if (/* tag */ typeof name === "number" || typeof name === "string") {
      switch (name) {
        case /* If */ 40 :
          adv();
          expect(/* Lparen */ 30);
          const c = rel_expr();
          expect(/* Rparen */ 31);
          expect(/* Then */ 41);
          const th = stat_seq();
          const el = accept(/* Else */ 42) ? stat_seq() : /* [] */ 0;
          expect(/* Fi */ 43);
          return {
            TAG: /* SIf */ 3,
            _0: c,
            _1: th,
            _2: el
          };
        case /* While */ 44 :
          adv();
          expect(/* Lparen */ 30);
          const c$1 = rel_expr();
          expect(/* Rparen */ 31);
          expect(/* Do */ 45);
          const b = stat_seq();
          expect(/* Od */ 46);
          return {
            TAG: /* SWhile */ 4,
            _0: c$1,
            _1: b
          };
        case /* Repeat */ 47 :
          adv();
          const b$1 = stat_seq();
          expect(/* Until */ 48);
          expect(/* Lparen */ 30);
          const c$2 = rel_expr();
          expect(/* Rparen */ 31);
          return {
            TAG: /* SRepeat */ 5,
            _0: b$1,
            _1: c$2
          };
        case /* Call */ 49 :
          adv();
          const s = Caml_array.get(arr, i.contents);
          let name$1;
          if (/* tag */ typeof s === "number" || typeof s === "string" || s.TAG !== /* Id */ 2) {
            name$1 = Stdlib.failwith("id");
          } else {
            adv();
            name$1 = s._0;
          }
          expect(/* Lparen */ 30);
          let args;
          if (accept(/* Rparen */ 31)) {
            args = /* [] */ 0;
          } else {
            const a = rel_expr();
            const loop = function (_acc) {
              while (true) {
                const acc = _acc;
                if (!accept(/* Comma */ 36)) {
                  return Stdlib__List.rev({
                    hd: a,
                    tl: acc
                  });
                }
                _acc = {
                  hd: rel_expr(),
                  tl: acc
                };
                continue;
              };
            };
            const args$1 = loop(/* [] */ 0);
            expect(/* Rparen */ 31);
            args = args$1;
          }
          return {
            TAG: /* SCall */ 2,
            _0: name$1,
            _1: args
          };
        case /* Return */ 50 :
          adv();
          rel_expr();
          return {
            TAG: /* SCall */ 2,
            _0: "return",
            _1: /* [] */ 0
          };
        default:
          return Stdlib.failwith("expected statement");
      }
    } else {
      if (name.TAG !== /* Id */ 2) {
        return Stdlib.failwith("expected statement");
      }
      const name$2 = name._0;
      adv();
      if (accept(/* Lbrack */ 34)) {
        rel_expr();
        expect(/* Rbrack */ 35);
        const match = adv();
        let op;
        if (/* tag */ typeof match === "number" || typeof match === "string") {
          switch (match) {
            case /* Assign */ 15 :
              op = /* A_ASSIGN */ 0;
              break;
            case /* AddAssign */ 16 :
              op = /* A_ADD */ 1;
              break;
            case /* SubAssign */ 17 :
              op = /* A_SUB */ 2;
              break;
            case /* MulAssign */ 18 :
              op = /* A_MUL */ 3;
              break;
            case /* DivAssign */ 19 :
              op = /* A_DIV */ 4;
              break;
            case /* ModAssign */ 20 :
              op = /* A_MOD */ 5;
              break;
            case /* PowAssign */ 21 :
              op = /* A_POW */ 6;
              break;
            default:
              op = Stdlib.failwith("unexpected assign op");
          }
        } else {
          op = Stdlib.failwith("unexpected assign op");
        }
        rel_expr();
        return {
          TAG: /* SAssign */ 0,
          _0: name$2,
          _1: op,
          _2: {
            TAG: /* ELit */ 0,
            _0: /* VVoid */ 0
          }
        };
      }
      if (accept(/* Inc */ 22)) {
        return {
          TAG: /* SUnary */ 1,
          _0: name$2,
          _1: /* U_INC */ 0
        };
      }
      if (accept(/* Dec */ 23)) {
        return {
          TAG: /* SUnary */ 1,
          _0: name$2,
          _1: /* U_DEC */ 1
        };
      }
      const match$1 = adv();
      let op$1;
      if (/* tag */ typeof match$1 === "number" || typeof match$1 === "string") {
        switch (match$1) {
          case /* Assign */ 15 :
            op$1 = /* A_ASSIGN */ 0;
            break;
          case /* AddAssign */ 16 :
            op$1 = /* A_ADD */ 1;
            break;
          case /* SubAssign */ 17 :
            op$1 = /* A_SUB */ 2;
            break;
          case /* MulAssign */ 18 :
            op$1 = /* A_MUL */ 3;
            break;
          case /* DivAssign */ 19 :
            op$1 = /* A_DIV */ 4;
            break;
          case /* ModAssign */ 20 :
            op$1 = /* A_MOD */ 5;
            break;
          case /* PowAssign */ 21 :
            op$1 = /* A_POW */ 6;
            break;
          default:
            op$1 = Stdlib.failwith("unexpected assign op");
        }
      } else {
        op$1 = Stdlib.failwith("unexpected assign op");
      }
      return {
        TAG: /* SAssign */ 0,
        _0: name$2,
        _1: op$1,
        _2: rel_expr()
      };
    }
  };
  const stat_seq = function (param) {
    let stmts = /* [] */ 0;
    stmts = {
      hd: statement(),
      tl: stmts
    };
    expect(/* Semi */ 38);
    while ((function () {
        const match = Caml_array.get(arr, i.contents);
        let tmp;
        if (/* tag */ typeof match === "number" || typeof match === "string") {
          switch (match) {
            case /* If */ 40 :
            case /* While */ 44 :
            case /* Repeat */ 47 :
            case /* Call */ 49 :
            case /* Return */ 50 :
              tmp = true;
              break;
            default:
              tmp = false;
          }
        } else {
          tmp = match.TAG === /* Id */ 2 ? true : false;
        }
        return tmp;
      })()) {
      stmts = {
        hd: statement(),
        tl: stmts
      };
      expect(/* Semi */ 38);
    };
    return Stdlib__List.rev(stmts);
  };
  expect(/* Main */ 51);
  while (is_type() && !Caml_obj.caml_equal(Caml_array.get(arr, i.contents), /* Void */ 24)) {
    adv();
    while (accept(/* Lbrack */ 34)) {
      rel_expr();
      expect(/* Rbrack */ 35);
    };
    while (is_id() || accept(/* Comma */ 36)) {
      if (is_id()) {
        adv();
      }
      
    };
    expect(/* Semi */ 38);
  };
  while (accept(/* Func */ 52)) {
    if (is_id()) {
      adv();
    }
    expect(/* Lparen */ 30);
    while (!accept(/* Rparen */ 31)) {
      if (!accept(/* Comma */ 36)) {
        if (is_type()) {
          adv();
        }
        while (accept(/* Lbrack */ 34)) {
          expect(/* Rbrack */ 35);
        };
        if (is_id()) {
          adv();
        }
        
      }
      
    };
    expect(/* Colon */ 37);
    if (is_type()) {
      adv();
    }
    expect(/* Lbrace */ 32);
    while (!accept(/* Rbrace */ 33)) {
      statement();
      expect(/* Semi */ 38);
    };
    expect(/* Semi */ 38);
  };
  expect(/* Lbrace */ 32);
  const body = stat_seq();
  expect(/* Rbrace */ 33);
  expect(/* Dot */ 39);
  return body;
}

function string_of_value(n) {
  if (/* tag */ typeof n === "number" || typeof n === "string") {
    return "void";
  }
  switch (n.TAG) {
    case /* VInt */ 0 :
      return String(n._0);
    case /* VFloat */ 1 :
      return Curry._1(Stdlib__Printf.sprintf({
        TAG: /* Format */ 0,
        _0: {
          TAG: /* Float */ 8,
          _0: [
            /* Float_flag_ */ 0,
            /* Float_f */ 0
          ],
          _1: /* No_padding */ 0,
          _2: {
            TAG: /* Lit_precision */ 0,
            _0: 2
          },
          _3: /* End_of_format */ 0
        },
        _1: "%.2f"
      }), n._0);
    case /* VBool */ 2 :
      return Stdlib.string_of_bool(n._0);
  }
}

function $$eval(env, e) {
  switch (e.TAG) {
    case /* ELit */ 0 :
      return e._0;
    case /* EVar */ 1 :
      try {
        return Stdlib__List.assoc(e._0, env.contents);
      }
      catch (raw_exn){
        const exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
        if (exn.MEL_EXN_ID === Stdlib.Not_found) {
          return {
            TAG: /* VInt */ 0,
            _0: 0
          };
        }
        throw exn;
      }
    case /* ENot */ 2 :
      const b = $$eval(env, e._0);
      if (/* tag */ typeof b === "number" || typeof b === "string" || b.TAG !== /* VBool */ 2) {
        return Stdlib.failwith("not: expected bool");
      } else {
        return {
          TAG: /* VBool */ 2,
          _0: !b._0
        };
      }
    case /* EBin */ 3 :
      return binop($$eval(env, e._0), e._1, $$eval(env, e._2));
    case /* ECall */ 4 :
      return builtin(e._0, Stdlib__List.map((function (param) {
        return $$eval(env, param);
      }), e._1));
  }
}

function binop(a, op, b) {
  if (/* tag */ typeof a === "number" || typeof a === "string") {
    return Stdlib.failwith("type error in binop");
  }
  switch (a.TAG) {
    case /* VInt */ 0 :
      if (/* tag */ typeof b === "number" || typeof b === "string") {
        return Stdlib.failwith("type error in binop");
      }
      if (b.TAG !== /* VInt */ 0) {
        return Stdlib.failwith("type error in binop");
      }
      const y = b._0;
      const x = a._0;
      if (!/* tag */ (typeof op === "number" || typeof op === "string")) {
        return Stdlib.failwith("type error in binop");
      }
      switch (op) {
        case /* Pow */ 3 :
          return {
            TAG: /* VInt */ 0,
            _0: Math.pow(x, y) | 0
          };
        case /* Mul */ 4 :
          return {
            TAG: /* VInt */ 0,
            _0: Math.imul(x, y)
          };
        case /* Div */ 5 :
          return {
            TAG: /* VInt */ 0,
            _0: Caml_int32.div(x, y)
          };
        case /* Mod */ 6 :
          return {
            TAG: /* VInt */ 0,
            _0: Caml_int32.mod_(x, y)
          };
        case /* Add */ 7 :
          return {
            TAG: /* VInt */ 0,
            _0: x + y | 0
          };
        case /* Sub */ 8 :
          return {
            TAG: /* VInt */ 0,
            _0: x - y | 0
          };
        case /* Eq */ 9 :
          return {
            TAG: /* VBool */ 2,
            _0: x === y
          };
        case /* Neq */ 10 :
          return {
            TAG: /* VBool */ 2,
            _0: x !== y
          };
        case /* Lt */ 11 :
          return {
            TAG: /* VBool */ 2,
            _0: x < y
          };
        case /* Le */ 12 :
          return {
            TAG: /* VBool */ 2,
            _0: x <= y
          };
        case /* Gt */ 13 :
          return {
            TAG: /* VBool */ 2,
            _0: x > y
          };
        case /* Ge */ 14 :
          return {
            TAG: /* VBool */ 2,
            _0: x >= y
          };
        default:
          return Stdlib.failwith("type error in binop");
      }
    case /* VFloat */ 1 :
      if (/* tag */ typeof b === "number" || typeof b === "string") {
        return Stdlib.failwith("type error in binop");
      }
      if (b.TAG !== /* VFloat */ 1) {
        return Stdlib.failwith("type error in binop");
      }
      const y$1 = b._0;
      const x$1 = a._0;
      if (!/* tag */ (typeof op === "number" || typeof op === "string")) {
        return Stdlib.failwith("type error in binop");
      }
      switch (op) {
        case /* Pow */ 3 :
          return {
            TAG: /* VFloat */ 1,
            _0: Math.pow(x$1, y$1)
          };
        case /* Mul */ 4 :
          return {
            TAG: /* VFloat */ 1,
            _0: x$1 * y$1
          };
        case /* Div */ 5 :
          return {
            TAG: /* VFloat */ 1,
            _0: x$1 / y$1
          };
        case /* Mod */ 6 :
          return {
            TAG: /* VFloat */ 1,
            _0: x$1 % y$1
          };
        case /* Add */ 7 :
          return {
            TAG: /* VFloat */ 1,
            _0: x$1 + y$1
          };
        case /* Sub */ 8 :
          return {
            TAG: /* VFloat */ 1,
            _0: x$1 - y$1
          };
        case /* Eq */ 9 :
          return {
            TAG: /* VBool */ 2,
            _0: x$1 === y$1
          };
        case /* Neq */ 10 :
          return {
            TAG: /* VBool */ 2,
            _0: x$1 !== y$1
          };
        case /* Lt */ 11 :
          return {
            TAG: /* VBool */ 2,
            _0: x$1 < y$1
          };
        case /* Le */ 12 :
          return {
            TAG: /* VBool */ 2,
            _0: x$1 <= y$1
          };
        case /* Gt */ 13 :
          return {
            TAG: /* VBool */ 2,
            _0: x$1 > y$1
          };
        case /* Ge */ 14 :
          return {
            TAG: /* VBool */ 2,
            _0: x$1 >= y$1
          };
        default:
          return Stdlib.failwith("type error in binop");
      }
    case /* VBool */ 2 :
      if (/* tag */ typeof b === "number" || typeof b === "string") {
        return Stdlib.failwith("type error in binop");
      }
      if (b.TAG !== /* VBool */ 2) {
        return Stdlib.failwith("type error in binop");
      }
      const y$2 = b._0;
      const x$2 = a._0;
      if (!/* tag */ (typeof op === "number" || typeof op === "string")) {
        return Stdlib.failwith("type error in binop");
      }
      switch (op) {
        case /* And */ 0 :
          return {
            TAG: /* VBool */ 2,
            _0: x$2 && y$2
          };
        case /* Or */ 1 :
          return {
            TAG: /* VBool */ 2,
            _0: x$2 || y$2
          };
        case /* Eq */ 9 :
          return {
            TAG: /* VBool */ 2,
            _0: x$2 === y$2
          };
        case /* Pow */ 3 :
        case /* Neq */ 10 :
          return {
            TAG: /* VBool */ 2,
            _0: x$2 !== y$2
          };
        default:
          return Stdlib.failwith("type error in binop");
      }
  }
}

function builtin(name, args) {
  switch (name) {
    case "printInt" :
      if (!args) {
        return /* VVoid */ 0;
      }
      const n = args.hd;
      if (/* tag */ typeof n === "number" || typeof n === "string" || !(n.TAG === /* VInt */ 0 && !args.tl)) {
        return /* VVoid */ 0;
      } else {
        return {
          TAG: /* VInt */ 0,
          _0: n._0
        };
      }
    default:
      return /* VVoid */ 0;
  }
}

function run(source) {
  try {
    const tokens = Coco_lib__Lexer.scan(source);
    const stmts = parse(tokens);
    const env = {
      contents: /* [] */ 0
    };
    const buf = Stdlib__Buffer.create(256);
    const exec = function (stmts) {
      Stdlib__List.iter((function (s) {
        switch (s.TAG) {
          case /* SAssign */ 0 :
            const n = s._0;
            switch (s._1) {
              case /* A_ASSIGN */ 0 :
                const v = $$eval(env, s._2);
                env.contents = {
                  hd: [
                    n,
                    v
                  ],
                  tl: Stdlib__List.remove_assoc(n, env.contents)
                };
                return;
              case /* A_ADD */ 1 :
                let old;
                try {
                  old = Stdlib__List.assoc(n, env.contents);
                }
                catch (raw_exn){
                  const exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
                  if (exn.MEL_EXN_ID === Stdlib.Not_found) {
                    old = {
                      TAG: /* VInt */ 0,
                      _0: 0
                    };
                  } else {
                    throw exn;
                  }
                }
                const v$1 = binop(old, /* Add */ 7, $$eval(env, s._2));
                env.contents = {
                  hd: [
                    n,
                    v$1
                  ],
                  tl: Stdlib__List.remove_assoc(n, env.contents)
                };
                return;
              case /* A_SUB */ 2 :
                let old$1;
                try {
                  old$1 = Stdlib__List.assoc(n, env.contents);
                }
                catch (raw_exn$1){
                  const exn$1 = Caml_js_exceptions.internalToOCamlException(raw_exn$1);
                  if (exn$1.MEL_EXN_ID === Stdlib.Not_found) {
                    old$1 = {
                      TAG: /* VInt */ 0,
                      _0: 0
                    };
                  } else {
                    throw exn$1;
                  }
                }
                const v$2 = binop(old$1, /* Sub */ 8, $$eval(env, s._2));
                env.contents = {
                  hd: [
                    n,
                    v$2
                  ],
                  tl: Stdlib__List.remove_assoc(n, env.contents)
                };
                return;
              case /* A_MUL */ 3 :
                let old$2;
                try {
                  old$2 = Stdlib__List.assoc(n, env.contents);
                }
                catch (raw_exn$2){
                  const exn$2 = Caml_js_exceptions.internalToOCamlException(raw_exn$2);
                  if (exn$2.MEL_EXN_ID === Stdlib.Not_found) {
                    old$2 = {
                      TAG: /* VInt */ 0,
                      _0: 0
                    };
                  } else {
                    throw exn$2;
                  }
                }
                const v$3 = binop(old$2, /* Mul */ 4, $$eval(env, s._2));
                env.contents = {
                  hd: [
                    n,
                    v$3
                  ],
                  tl: Stdlib__List.remove_assoc(n, env.contents)
                };
                return;
              case /* A_DIV */ 4 :
                let old$3;
                try {
                  old$3 = Stdlib__List.assoc(n, env.contents);
                }
                catch (raw_exn$3){
                  const exn$3 = Caml_js_exceptions.internalToOCamlException(raw_exn$3);
                  if (exn$3.MEL_EXN_ID === Stdlib.Not_found) {
                    old$3 = {
                      TAG: /* VInt */ 0,
                      _0: 0
                    };
                  } else {
                    throw exn$3;
                  }
                }
                const v$4 = binop(old$3, /* Div */ 5, $$eval(env, s._2));
                env.contents = {
                  hd: [
                    n,
                    v$4
                  ],
                  tl: Stdlib__List.remove_assoc(n, env.contents)
                };
                return;
              case /* A_MOD */ 5 :
                let old$4;
                try {
                  old$4 = Stdlib__List.assoc(n, env.contents);
                }
                catch (raw_exn$4){
                  const exn$4 = Caml_js_exceptions.internalToOCamlException(raw_exn$4);
                  if (exn$4.MEL_EXN_ID === Stdlib.Not_found) {
                    old$4 = {
                      TAG: /* VInt */ 0,
                      _0: 0
                    };
                  } else {
                    throw exn$4;
                  }
                }
                const v$5 = binop(old$4, /* Mod */ 6, $$eval(env, s._2));
                env.contents = {
                  hd: [
                    n,
                    v$5
                  ],
                  tl: Stdlib__List.remove_assoc(n, env.contents)
                };
                return;
              case /* A_POW */ 6 :
                let old$5;
                try {
                  old$5 = Stdlib__List.assoc(n, env.contents);
                }
                catch (raw_exn$5){
                  const exn$5 = Caml_js_exceptions.internalToOCamlException(raw_exn$5);
                  if (exn$5.MEL_EXN_ID === Stdlib.Not_found) {
                    old$5 = {
                      TAG: /* VInt */ 0,
                      _0: 0
                    };
                  } else {
                    throw exn$5;
                  }
                }
                const v$6 = binop(old$5, /* Pow */ 3, $$eval(env, s._2));
                env.contents = {
                  hd: [
                    n,
                    v$6
                  ],
                  tl: Stdlib__List.remove_assoc(n, env.contents)
                };
                return;
            }
          case /* SUnary */ 1 :
            const n$1 = s._0;
            if (s._1 === /* U_INC */ 0) {
              let old$6;
              try {
                old$6 = Stdlib__List.assoc(n$1, env.contents);
              }
              catch (raw_exn$6){
                const exn$6 = Caml_js_exceptions.internalToOCamlException(raw_exn$6);
                if (exn$6.MEL_EXN_ID === Stdlib.Not_found) {
                  old$6 = {
                    TAG: /* VInt */ 0,
                    _0: 0
                  };
                } else {
                  throw exn$6;
                }
              }
              const v$7 = binop(old$6, /* Add */ 7, {
                TAG: /* VInt */ 0,
                _0: 1
              });
              env.contents = {
                hd: [
                  n$1,
                  v$7
                ],
                tl: Stdlib__List.remove_assoc(n$1, env.contents)
              };
              return;
            }
            let old$7;
            try {
              old$7 = Stdlib__List.assoc(n$1, env.contents);
            }
            catch (raw_exn$7){
              const exn$7 = Caml_js_exceptions.internalToOCamlException(raw_exn$7);
              if (exn$7.MEL_EXN_ID === Stdlib.Not_found) {
                old$7 = {
                  TAG: /* VInt */ 0,
                  _0: 0
                };
              } else {
                throw exn$7;
              }
            }
            const v$8 = binop(old$7, /* Sub */ 8, {
              TAG: /* VInt */ 0,
              _0: 1
            });
            env.contents = {
              hd: [
                n$1,
                v$8
              ],
              tl: Stdlib__List.remove_assoc(n$1, env.contents)
            };
            return;
          case /* SCall */ 2 :
            const vs = Stdlib__List.map((function (param) {
              return $$eval(env, param);
            }), s._1);
            let name = s._0;
            switch (name) {
              case "printBool" :
                if (vs) {
                  const b = vs.hd;
                  let exit = 0;
                  if (/* tag */ typeof b === "number" || typeof b === "string" || b.TAG !== /* VBool */ 2) {
                    exit = 2;
                  } else if (!vs.tl) {
                    Stdlib__Buffer.add_string(buf, Stdlib.string_of_bool(b._0));
                    return Stdlib__Buffer.add_char(buf, /* ' ' */32);
                  }
                  if (exit === 2 && !vs.tl) {
                    Stdlib__Buffer.add_string(buf, string_of_value(b));
                    return Stdlib__Buffer.add_char(buf, /* ' ' */32);
                  }
                  
                }
                break;
              case "printFloat" :
                if (vs) {
                  const f = vs.hd;
                  let exit$1 = 0;
                  if (/* tag */ typeof f === "number" || typeof f === "string" || f.TAG !== /* VFloat */ 1) {
                    exit$1 = 2;
                  } else if (!vs.tl) {
                    return Stdlib__Buffer.add_string(buf, Curry._1(Stdlib__Printf.sprintf({
                      TAG: /* Format */ 0,
                      _0: {
                        TAG: /* Float */ 8,
                        _0: [
                          /* Float_flag_ */ 0,
                          /* Float_f */ 0
                        ],
                        _1: /* No_padding */ 0,
                        _2: {
                          TAG: /* Lit_precision */ 0,
                          _0: 2
                        },
                        _3: {
                          TAG: /* Char_literal */ 12,
                          _0: /* ' ' */32,
                          _1: /* End_of_format */ 0
                        }
                      },
                      _1: "%.2f "
                    }), f._0));
                  }
                  if (exit$1 === 2 && !vs.tl) {
                    Stdlib__Buffer.add_string(buf, string_of_value(f));
                    return Stdlib__Buffer.add_char(buf, /* ' ' */32);
                  }
                  
                }
                break;
              case "printInt" :
                if (vs) {
                  const n$2 = vs.hd;
                  let exit$2 = 0;
                  if (/* tag */ typeof n$2 === "number" || typeof n$2 === "string" || n$2.TAG !== /* VInt */ 0) {
                    exit$2 = 2;
                  } else if (!vs.tl) {
                    Stdlib__Buffer.add_string(buf, String(n$2._0));
                    return Stdlib__Buffer.add_char(buf, /* ' ' */32);
                  }
                  if (exit$2 === 2 && !vs.tl) {
                    Stdlib__Buffer.add_string(buf, string_of_value(n$2));
                    return Stdlib__Buffer.add_char(buf, /* ' ' */32);
                  }
                  
                }
                break;
              case "println" :
                if (!vs) {
                  return Stdlib__Buffer.add_char(buf, /* '\n' */10);
                }
                break;
              case "readBool" :
              case "readFloat" :
              case "readInt" :
                if (!vs) {
                  return;
                }
                break;
              case "return" :
                return;
            }
            return Stdlib.failwith("unknown function: " + (name + (" with " + (String(Stdlib__List.length(vs)) + " args"))));
          case /* SIf */ 3 :
            const match = $$eval(env, s._0);
            if (/* tag */ typeof match === "number" || typeof match === "string" || match.TAG !== /* VBool */ 2) {
              return Stdlib.failwith("if: expected bool");
            } else if (match._0) {
              return exec(s._1);
            } else {
              return exec(s._2);
            }
          case /* SWhile */ 4 :
            const b$1 = s._1;
            const c = s._0;
            let _param;
            while (true) {
              const match$1 = $$eval(env, c);
              if (/* tag */ typeof match$1 === "number" || typeof match$1 === "string") {
                return Stdlib.failwith("while: expected bool");
              }
              if (match$1.TAG !== /* VBool */ 2) {
                return Stdlib.failwith("while: expected bool");
              }
              if (!match$1._0) {
                return;
              }
              exec(b$1);
              _param = undefined;
              continue;
            };
          case /* SRepeat */ 5 :
            const c$1 = s._1;
            const b$2 = s._0;
            let _param$1;
            while (true) {
              exec(b$2);
              const match$2 = $$eval(env, c$1);
              if (/* tag */ typeof match$2 === "number" || typeof match$2 === "string") {
                return Stdlib.failwith("until: expected bool");
              }
              if (match$2.TAG !== /* VBool */ 2) {
                return Stdlib.failwith("until: expected bool");
              }
              if (match$2._0) {
                return;
              }
              _param$1 = undefined;
              continue;
            };
        }
      }), stmts);
    };
    exec(stmts);
    return Stdlib__Buffer.contents(buf);
  }
  catch (raw_msg){
    const msg = Caml_js_exceptions.internalToOCamlException(raw_msg);
    if (msg.MEL_EXN_ID === Stdlib.Failure) {
      return "Error: " + msg._1;
    } else {
      return "Error: " + Stdlib__Printexc.to_string(msg);
    }
  }
}

const to_string = Coco_lib__Token.to_string;

const kw = Coco_lib__Token.kw;

const scan = Coco_lib__Lexer.scan;

export {
  to_string,
  kw,
  scan,
  parse,
  string_of_value,
  $$eval,
  binop,
  builtin,
  run,
}
/* Stdlib__Printexc Not a pure module */
