// Generated by Melange

import * as Caml_bytes from "melange.js/caml_bytes.js";
import * as Caml_format from "melange.js/caml_format.js";
import * as Caml_js_exceptions from "melange.js/caml_js_exceptions.js";
import * as Caml_string from "melange.js/caml_string.js";
import * as Coco_lib__Token from "./token.js";
import * as Curry from "melange.js/curry.js";
import * as Stdlib from "melange/stdlib.js";
import * as Stdlib__Bytes from "melange/bytes.js";
import * as Stdlib__List from "melange/list.js";
import * as Stdlib__Printf from "melange/printf.js";
import * as Stdlib__String from "melange/string.js";

function scan(src) {
  const len = src.length;
  const i = {
    contents: 0
  };
  const ts = {
    contents: /* [] */ 0
  };
  const peek = function (param) {
    if (i.contents < len) {
      return Caml_string.get(src, i.contents);
    }
    
  };
  const adv = function (param) {
    const c = Caml_string.get(src, i.contents);
    i.contents = i.contents + 1 | 0;
    return c;
  };
  const eat = function (p) {
    const b = Caml_bytes.caml_create_bytes(32);
    let j = 0;
    while ((function () {
        const c = peek();
        if (c !== undefined && Curry._1(p, c)) {
          return true;
        } else {
          return false;
        }
      })()) {
      Caml_bytes.set(b, j, adv());
      j = j + 1 | 0;
    };
    return Stdlib__Bytes.sub_string(b, 0, j);
  };
  const push = function (tok) {
    ts.contents = {
      hd: tok,
      tl: ts.contents
    };
  };
  const skip_ws = function (_param) {
    while (true) {
      const match = peek();
      if (match === undefined) {
        return;
      }
      if (match > 13 || match < 9) {
        if (match !== 32) {
          return;
        }
        adv();
        _param = undefined;
        continue;
      }
      if (match === 12 || match === 11) {
        return;
      }
      adv();
      _param = undefined;
      continue;
    };
  };
  const next = function (_param) {
    while (true) {
      skip_ws();
      const c = peek();
      if (c === undefined) {
        return push(/* Eof */ 53);
      }
      if (c >= /* 'a' */97 && c <= /* 'z' */122 || c >= /* 'A' */65 && c <= /* 'Z' */90) {
        const s = eat(function (c) {
          if (c >= /* 'a' */97 && c <= /* 'z' */122 || c >= /* 'A' */65 && c <= /* 'Z' */90 || c >= /* '0' */48 && c <= /* '9' */57) {
            return true;
          } else {
            return c === /* '_' */95;
          }
        });
        let tmp;
        try {
          tmp = Stdlib__List.assoc(s, Coco_lib__Token.kw);
        }
        catch (raw_exn){
          const exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
          if (exn.MEL_EXN_ID === Stdlib.Not_found) {
            tmp = {
              TAG: /* Id */ 2,
              _0: s
            };
          } else {
            throw exn;
          }
        }
        return push(tmp);
      }
      if (c >= /* '0' */48 && c <= /* '9' */57 || c === /* '-' */45 && (i.contents + 1 | 0) < len && Caml_string.get(src, i.contents + 1 | 0) >= /* '0' */48 && Caml_string.get(src, i.contents + 1 | 0) <= /* '9' */57) {
        const s$1 = eat(function (c) {
          if (c >= /* '0' */48 && c <= /* '9' */57 || c === /* '.' */46) {
            return true;
          } else {
            return c === /* '-' */45;
          }
        });
        if (Stdlib__String.contains(s$1, /* '.' */46)) {
          return push({
            TAG: /* FloatVal */ 1,
            _0: Caml_format.caml_float_of_string(s$1)
          });
        } else {
          return push({
            TAG: /* IntVal */ 0,
            _0: Caml_format.caml_int_of_string(s$1)
          });
        }
      }
      if (c !== 47) {
        adv();
        let tmp$1;
        let exit = 0;
        if (c >= 95) {
          switch (c) {
            case 123 :
              tmp$1 = /* Lbrace */ 32;
              break;
            case 125 :
              tmp$1 = /* Rbrace */ 33;
              break;
            default:
              exit = 1;
          }
        } else if (c >= 33) {
          switch (c) {
            case 33 :
              const match = peek();
              if (match === 61) {
                adv();
                tmp$1 = /* Neq */ 10;
              } else {
                tmp$1 = Stdlib.failwith("stray !");
              }
              break;
            case 37 :
              const match$1 = peek();
              if (match$1 === 61) {
                adv();
                tmp$1 = /* ModAssign */ 20;
              } else {
                tmp$1 = /* Mod */ 6;
              }
              break;
            case 40 :
              tmp$1 = /* Lparen */ 30;
              break;
            case 41 :
              tmp$1 = /* Rparen */ 31;
              break;
            case 42 :
              const match$2 = peek();
              if (match$2 === 61) {
                adv();
                tmp$1 = /* MulAssign */ 18;
              } else {
                tmp$1 = /* Mul */ 4;
              }
              break;
            case 43 :
              const match$3 = peek();
              if (match$3 !== undefined) {
                if (match$3 !== 43) {
                  if (match$3 !== 61) {
                    tmp$1 = /* Add */ 7;
                  } else {
                    adv();
                    tmp$1 = /* AddAssign */ 16;
                  }
                } else {
                  adv();
                  tmp$1 = /* Inc */ 22;
                }
              } else {
                tmp$1 = /* Add */ 7;
              }
              break;
            case 44 :
              tmp$1 = /* Comma */ 36;
              break;
            case 45 :
              const match$4 = peek();
              if (match$4 !== undefined) {
                if (match$4 !== 45) {
                  if (match$4 !== 61) {
                    tmp$1 = /* Sub */ 8;
                  } else {
                    adv();
                    tmp$1 = /* SubAssign */ 17;
                  }
                } else {
                  adv();
                  tmp$1 = /* Dec */ 23;
                }
              } else {
                tmp$1 = /* Sub */ 8;
              }
              break;
            case 46 :
              tmp$1 = /* Dot */ 39;
              break;
            case 58 :
              tmp$1 = /* Colon */ 37;
              break;
            case 59 :
              tmp$1 = /* Semi */ 38;
              break;
            case 60 :
              const match$5 = peek();
              if (match$5 === 61) {
                adv();
                tmp$1 = /* Le */ 12;
              } else {
                tmp$1 = /* Lt */ 11;
              }
              break;
            case 61 :
              const match$6 = peek();
              if (match$6 === 61) {
                adv();
                tmp$1 = /* Eq */ 9;
              } else {
                tmp$1 = /* Assign */ 15;
              }
              break;
            case 62 :
              const match$7 = peek();
              if (match$7 === 61) {
                adv();
                tmp$1 = /* Ge */ 14;
              } else {
                tmp$1 = /* Gt */ 13;
              }
              break;
            case 91 :
              tmp$1 = /* Lbrack */ 34;
              break;
            case 34 :
            case 35 :
            case 36 :
            case 38 :
            case 39 :
            case 47 :
            case 48 :
            case 49 :
            case 50 :
            case 51 :
            case 52 :
            case 53 :
            case 54 :
            case 55 :
            case 56 :
            case 57 :
            case 63 :
            case 64 :
            case 65 :
            case 66 :
            case 67 :
            case 68 :
            case 69 :
            case 70 :
            case 71 :
            case 72 :
            case 73 :
            case 74 :
            case 75 :
            case 76 :
            case 77 :
            case 78 :
            case 79 :
            case 80 :
            case 81 :
            case 82 :
            case 83 :
            case 84 :
            case 85 :
            case 86 :
            case 87 :
            case 88 :
            case 89 :
            case 90 :
            case 92 :
              exit = 1;
              break;
            case 93 :
              tmp$1 = /* Rbrack */ 35;
              break;
            case 94 :
              const match$8 = peek();
              if (match$8 === 61) {
                adv();
                tmp$1 = /* PowAssign */ 21;
              } else {
                tmp$1 = /* Pow */ 3;
              }
              break;
          }
        } else {
          exit = 1;
        }
        if (exit === 1) {
          tmp$1 = Stdlib.failwith(Curry._1(Stdlib__Printf.sprintf({
            TAG: /* Format */ 0,
            _0: {
              TAG: /* String_literal */ 11,
              _0: "unexpected char: ",
              _1: {
                TAG: /* Char */ 0,
                _0: /* End_of_format */ 0
              }
            },
            _1: "unexpected char: %c"
          }), c));
        }
        return push(tmp$1);
      }
      adv();
      const match$9 = peek();
      if (match$9 === undefined) {
        return push(/* Div */ 5);
      }
      if (match$9 !== 42) {
        if (match$9 !== 47) {
          if (match$9 !== 61) {
            return push(/* Div */ 5);
          } else {
            adv();
            return push(/* DivAssign */ 19);
          }
        }
        eat(function (c) {
          return c !== /* '\n' */10;
        });
        _param = undefined;
        continue;
      }
      adv();
      const skip_block = function (_param) {
        while (true) {
          if (i.contents >= len) {
            return;
          }
          let tmp = false;
          if (adv() === /* '*' */42) {
            const match = peek();
            tmp = match !== undefined ? match === 47 : false;
          }
          if (tmp) {
            adv();
            return;
          }
          _param = undefined;
          continue;
        };
      };
      skip_block();
      _param = undefined;
      continue;
    };
  };
  while (i.contents < len) {
    next();
  };
  return Stdlib__List.rev({
    hd: /* Eof */ 53,
    tl: ts.contents
  });
}

export {
  scan,
}
/* No side effect */
