// Generated by Melange

import * as Stdlib from "melange/stdlib.js";

function to_string(n) {
  if (/* tag */ typeof n === "number" || typeof n === "string") {
    switch (n) {
      case /* And */ 0 :
        return "and";
      case /* Or */ 1 :
        return "or";
      case /* Not */ 2 :
        return "not";
      case /* Pow */ 3 :
        return "^";
      case /* Mul */ 4 :
        return "*";
      case /* Div */ 5 :
        return "/";
      case /* Mod */ 6 :
        return "%";
      case /* Add */ 7 :
        return "+";
      case /* Sub */ 8 :
        return "-";
      case /* Eq */ 9 :
        return "==";
      case /* Neq */ 10 :
        return "!=";
      case /* Lt */ 11 :
        return "<";
      case /* Le */ 12 :
        return "<=";
      case /* Gt */ 13 :
        return ">";
      case /* Ge */ 14 :
        return ">=";
      case /* Assign */ 15 :
        return "=";
      case /* AddAssign */ 16 :
        return "+=";
      case /* SubAssign */ 17 :
        return "-=";
      case /* MulAssign */ 18 :
        return "*=";
      case /* DivAssign */ 19 :
        return "/=";
      case /* ModAssign */ 20 :
        return "%=";
      case /* PowAssign */ 21 :
        return "^=";
      case /* Inc */ 22 :
        return "++";
      case /* Dec */ 23 :
        return "--";
      case /* Void */ 24 :
        return "void";
      case /* Bool */ 25 :
        return "bool";
      case /* Int */ 26 :
        return "int";
      case /* Float */ 27 :
        return "float";
      case /* True */ 28 :
        return "true";
      case /* False */ 29 :
        return "false";
      case /* Lparen */ 30 :
        return "(";
      case /* Rparen */ 31 :
        return ")";
      case /* Lbrace */ 32 :
        return "{";
      case /* Rbrace */ 33 :
        return "}";
      case /* Lbrack */ 34 :
        return "[";
      case /* Rbrack */ 35 :
        return "]";
      case /* Comma */ 36 :
        return ",";
      case /* Colon */ 37 :
        return ":";
      case /* Semi */ 38 :
        return ";";
      case /* Dot */ 39 :
        return ".";
      case /* If */ 40 :
        return "if";
      case /* Then */ 41 :
        return "then";
      case /* Else */ 42 :
        return "else";
      case /* Fi */ 43 :
        return "fi";
      case /* While */ 44 :
        return "while";
      case /* Do */ 45 :
        return "do";
      case /* Od */ 46 :
        return "od";
      case /* Repeat */ 47 :
        return "repeat";
      case /* Until */ 48 :
        return "until";
      case /* Call */ 49 :
        return "call";
      case /* Return */ 50 :
        return "return";
      case /* Main */ 51 :
        return "main";
      case /* Func */ 52 :
        return "function";
      case /* Eof */ 53 :
        return "EOF";
    }
  } else {
    switch (n.TAG) {
      case /* IntVal */ 0 :
        return String(n._0);
      case /* FloatVal */ 1 :
        return Stdlib.string_of_float(n._0);
      case /* Id */ 2 :
        return n._0;
    }
  }
}

const kw = {
  hd: [
    "and",
    /* And */ 0
  ],
  tl: {
    hd: [
      "or",
      /* Or */ 1
    ],
    tl: {
      hd: [
        "not",
        /* Not */ 2
      ],
      tl: {
        hd: [
          "void",
          /* Void */ 24
        ],
        tl: {
          hd: [
            "bool",
            /* Bool */ 25
          ],
          tl: {
            hd: [
              "int",
              /* Int */ 26
            ],
            tl: {
              hd: [
                "float",
                /* Float */ 27
              ],
              tl: {
                hd: [
                  "true",
                  /* True */ 28
                ],
                tl: {
                  hd: [
                    "false",
                    /* False */ 29
                  ],
                  tl: {
                    hd: [
                      "if",
                      /* If */ 40
                    ],
                    tl: {
                      hd: [
                        "then",
                        /* Then */ 41
                      ],
                      tl: {
                        hd: [
                          "else",
                          /* Else */ 42
                        ],
                        tl: {
                          hd: [
                            "fi",
                            /* Fi */ 43
                          ],
                          tl: {
                            hd: [
                              "while",
                              /* While */ 44
                            ],
                            tl: {
                              hd: [
                                "do",
                                /* Do */ 45
                              ],
                              tl: {
                                hd: [
                                  "od",
                                  /* Od */ 46
                                ],
                                tl: {
                                  hd: [
                                    "repeat",
                                    /* Repeat */ 47
                                  ],
                                  tl: {
                                    hd: [
                                      "until",
                                      /* Until */ 48
                                    ],
                                    tl: {
                                      hd: [
                                        "call",
                                        /* Call */ 49
                                      ],
                                      tl: {
                                        hd: [
                                          "return",
                                          /* Return */ 50
                                        ],
                                        tl: {
                                          hd: [
                                            "main",
                                            /* Main */ 51
                                          ],
                                          tl: {
                                            hd: [
                                              "function",
                                              /* Func */ 52
                                            ],
                                            tl: /* [] */ 0
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
};

export {
  to_string,
  kw,
}
/* No side effect */
